parametrize scheme version of the game of life

diff --git a/scm/life/run b/scm/life/run
--- a/scm/life/run
+++ b/scm/life/run
@@ -2,10 +2,10 @@
 
 # check for mpv
 type mpv > /dev/null 2>&1 || {
-    echo 'error : install mpv first' >&2
+    echo "error : install mpv first" >&2
     exit 1
 }
 
 ./make.sh
 
-./life | mpv - -fs -scale=nearest
+./life 150 150 5500 500 | mpv - -fs -scale=nearest
