make comments consistent with other programs

diff --git a/scm/life/run b/scm/life/run
--- a/scm/life/run
+++ b/scm/life/run
@@ -2,7 +2,7 @@
 
 # check for mpv
 type mpv > /dev/null 2>&1 || {
-    echo "error : install mpv first" >&2
+    echo 'error : install mpv first' >&2
     exit 1
 }
 
