update all the code & setup to current style

diff --git a/bash/ant/ant b/bash/ant/ant
--- a/bash/ant/ant
+++ b/bash/ant/ant
@@ -1,40 +1,84 @@
 #!/usr/bin/env bash
 #
-# ant - langton's ant implementation
+# ant - langton's ant
 
-cd "${0%.*}"; . ../main
+usage() {
+    while IFS= read -r line; do
+        printf '%s\n' "$line"
+    done << EOF
+usage : ${0##*/} [-whi <number>]
 
-usage="usage : ${0##*/} [height] [width] [iter]"
+options :
+    -w <number>    set width  to <number> (default : 15)
+    -h <number>    set height to <number> (default : 15)
+    -i <number>    iterate <number> times (default : 500)
+EOF
+} >&2
 
-helper X "$1"
-helper Y "$2"
-helper N "$3"
+convert_to_number() {
+    declare -n var=$1
+
+    { printf -v var '%d' "$2" &> /dev/null || ((var < 0)); } || {
+        echo "error : '$2' isn't a valid positive integer" >&2
+        exit 1
+    }
+}
+
+ant() {
+    declare -A uni
+
+    ((
+        ant_x = height / 2,
+        ant_y =  width / 2,
+        dir = 0
+    ))
+
+    for ((n = 0; n < iter; ++n)) {
+        printf 'P1\n%s %s\n' "$width" "$height"
+
+        for ((i = 0; i < height; ++i)) {
+            for ((j = 0; j < width; ++j)) {
+                printf '%s' $((uni[$i $j]))
+            }
+        }
+
+        ((dir = (dir + ((uni[$ant_x $ant_y] ^= 1) == 0 ? 1 : -1) + 4) % 4))
+
+        case $dir in
+            0) ((ant_x = (--ant_x + height) % height));;
+            1) ((ant_y = (--ant_y +  width) %  width));;
+            2) ((ant_x = (++ant_x + height) % height));;
+            3) ((ant_y = (++ant_y +  width) %  width));;
+        esac
+    }
+}
 
 ((
-    ANT_X = X / 2,
-    ANT_Y = Y / 2,
-    DIR = 0
+    width  = 15,
+    height = 15,
+    iter   = 500
 ))
 
-declare -A uni
+while (($#)); do
+    getopts ":w:h:i:" arg
 
-for ((n = 0; n < N; ++n)) {
-    out="P1\n$Y $X\n"
-
-    for ((i = 0; i < X; ++i)) {
-        for ((j = 0; j < Y; ++j)) {
-            out+=$((uni[$i $j]))
-        }
-    }
-
-    ((DIR = (DIR + ((uni[$ANT_X $ANT_Y] ^=1 ) == 0 ? 1 : -1) + 4) % 4))
-
-    case $DIR in
-        0) ((ANT_X = (--ANT_X + X) % X));;
-        1) ((ANT_Y = (++ANT_Y + Y) % Y));;
-        2) ((ANT_X = (++ANT_X + X) % X));;
-        3) ((ANT_Y = (--ANT_Y + Y) % Y))
+    case $arg in
+        w)
+            convert_to_number width  "$2"
+            shift
+            ;;
+        h)
+            convert_to_number height "$2"
+            shift
+            ;;
+        i)
+            convert_to_number iter   "$2"
+            shift
+            ;;
+        *) usage
     esac
 
-    printf '%b\n' "$out"
-}
+    shift
+done
+
+ant
diff --git a/bash/brain/brain b/bash/brain/brain
--- a/bash/brain/brain
+++ b/bash/brain/brain
@@ -1,70 +1,109 @@
 #!/usr/bin/env bash
 #
-# brain - brian's brain implementation
-
-cd "${0%.*}"; . ../main
+# brain - brian's brain
 
 COLORS=(
     '016 032 041'
     '113 170 197'
-    '237 238 240'
+    '201 100 126'
 )
 
-usage="usage : ${0##*/} [height] [width] [init] [iter]"
+usage() {
+    while IFS= read -r line; do
+        printf '%s\n' "$line"
+    done << EOF
+usage : ${0##*/} [-whi <number>]
 
-helper X "$1"
-helper Y "$2"
-helper I "$3"
-helper N "$4"
+options :
+    -w <number>    set width  to <number> (default : 15)
+    -h <number>    set height to <number> (default : 15)
+    -i <number>    iterate <number> times (default : 500)
+EOF
+} >&2
 
-declare -A uni
+convert_to_number() {
+    declare -n var=$1
 
-((t = 0))
-
-for ((i = 0; i < I; ++i)) {
-    ((
-        x = RANDOM % X,
-        y = RANDOM % Y
-    ))
-
-    ((uni[$x $y $t] = RANDOM % 2 + 1))
+    { printf -v var '%d' "$2" &> /dev/null || ((var < 0)); } || {
+        echo "error : '$2' isn't a valid positive integer" >&2
+        exit 1
+    }
 }
 
-for ((n = 0; n < N; ++n)) {
-    out="P3\n$Y $X\n255\n"
+brain() {
+    declare -A uni
 
-    for ((i = 0; i < X; ++i)) {
-        for ((j = 0; j < Y; ++j)) {
-            out+="${COLORS[uni[$i $j $t]]}\n"
+    ((flag = 0))
 
-            case $((uni[$i $j $t])) in
-                0)
+    for ((i = 0; i < height * width / 4; ++i)) {
+        ((uni[$((RANDOM % height)) $((RANDOM % width)) $flag] = RANDOM % 2 + 1))
+    }
+
+    for ((n = 0; n < iter; ++n)) {
+        printf 'P3\n%s %s\n255\n' "$width" "$height"
+
+        for ((i = 0; i < height; ++i)) {
+            for ((j = 0; j < width; ++j)) {
+                ((tmp = uni[$i $j $flag]))
+
+                printf '%s\n' "${COLORS[tmp]}"
+
+                ((tmp == 0)) && {
                     ((cnt = 0))
 
-                    for u in -1 0 1; {
-                        for v in -1 0 1; {
-                            ((u != 0 || v != 0)) && {
+                    for ((k = -1; k <= 1; ++k)) {
+                        for ((l = -1; l <= 1; ++l)) {
+                            ((k != 0 || l != 0)) && {
                                 ((
-                                    x = (i + u + X) % X,
-                                    y = (j + v + Y) % Y
+                                    x = (i + k + height) % height,
+                                    y = (j + l +  width) %  width
                                 ))
 
-                                ((uni[$x $y $t] == 2 && ++cnt))
+                                ((uni[$x $y $flag] == 2)) &&
+                                    ((++cnt))
                             }
                         }
                     }
-
                     ((tmp = cnt == 2 ? 2 : 0))
-                    ;;
-                1) ((tmp = 0));;
-                2) ((tmp = 1));;
-            esac
 
-            ((uni[$i $j $((!t))] = tmp))
+                    :
+                } ||
+                    ((--tmp))
+
+                ((uni[$i $j $((!flag))] = tmp))
+            }
         }
+
+        ((flag ^= 1))
     }
-
-    printf '%b\n' "$out"
-
-    ((t ^= 1))
 }
+
+((
+    width  = 15,
+    height = 15,
+    iter   = 500
+))
+
+while (($#)); do
+    getopts ":w:h:i:" arg
+
+    case $arg in
+        w)
+            convert_to_number width  "$2"
+            shift
+            ;;
+        h)
+            convert_to_number height "$2"
+            shift
+            ;;
+        i)
+            convert_to_number iter   "$2"
+            shift
+            ;;
+        *) usage
+    esac
+
+    shift
+done
+
+brain
diff --git a/bash/life/life b/bash/life/life
--- a/bash/life/life
+++ b/bash/life/life
@@ -1,62 +1,98 @@
 #!/usr/bin/env bash
 #
-# life - game of life implementation
+# life - game of life
 
-cd "${0%.*}"; . ../main
+usage() {
+    while IFS= read -r line; do
+        printf '%s\n' "$line"
+    done << EOF
+usage : ${0##*/} [-whi <number>]
 
-usage="usage : ${0##*/} [height] [width] [init] [iter]"
+options :
+    -w <number>    set width  to <number> (default : 15)
+    -h <number>    set height to <number> (default : 15)
+    -i <number>    iterate <number> times (default : 500)
+EOF
+} >&2
 
-helper X "$1"
-helper Y "$2"
-helper I "$3"
-helper N "$4"
+convert_to_number() {
+    declare -n var=$1
 
-declare -A uni
-
-((t = 0))
-
-for ((i = 0; i < I; ++i)) {
-    ((
-        x = RANDOM % X,
-        y = RANDOM % Y
-    ))
-
-    ((uni[$x $y $t] = 1))
+    { printf -v var '%d' "$2" &> /dev/null || ((var < 0)); } || {
+        echo "error : '$2' isn't a valid positive integer" >&2
+        exit 1
+    }
 }
 
-for ((n = 0; n < N; ++n)) {
-    out="P1\n$X $Y\n"
+life() {
+    declare -A uni
 
-    for ((i = 0; i < X; ++i)) {
-        for ((j = 0; j < Y; ++j)) {
-            out+=$((uni[$i $j $t]))
+    ((flag = 0))
 
-            ((cnt = 0))
-
-            for u in -1 0 1; {
-                for v in -1 0 1; {
-                    ((u != 0 || v != 0)) && {
-                        ((
-                            x = (i + u + X) % X,
-                            y = (j + v + Y) % Y
-                        ))
-
-                        ((uni[$x $y $t] == 1 && ++cnt))
-                    }
-                }
-            }
-
-            case $cnt in
-                2) ((tmp = uni[$i $j $t]));;
-                3) ((tmp = 1));;
-                *) ((tmp = 0));;
-            esac
-
-            ((uni[$i $j $((!t))] = tmp))
-        }
+    for ((i = 0; i < height * width / 4; ++i)) {
+        ((uni[$((RANDOM % height)) $((RANDOM % width)) $flag] = 1))
     }
 
-    printf '%b\n' "$out"
+    for ((n = 0; n < iter; ++n)) {
+        printf 'P1\n%s %s\n' "$width" "$height"
 
-    ((t ^= 1))
+        for ((i = 0; i < height; ++i)) {
+            for ((j = 0; j < width; ++j)) {
+                printf '%s' $((uni[$i $j $flag]))
+
+                ((cnt = 0))
+
+                for ((k = -1; k <= 1; ++k)) {
+                    for ((l = -1; l <= 1; ++l)) {
+                        ((k != 0 || l != 0)) && {
+                            ((
+                                x = (i + k + height) % height,
+                                y = (j + l +  width) %  width
+                            ))
+
+                            ((cnt += uni[$x $y $flag]))
+                        }
+                    }
+                }
+
+                case $cnt in
+                    2) ((uni[$i $j $((!flag))] = uni[$i $j $flag]));;
+                    3) ((uni[$i $j $((!flag))] = 1));;
+                    *) ((uni[$i $j $((!flag))] = 0))
+                esac
+            }
+        }
+
+        ((flag ^= 1))
+    }
 }
+
+((
+    width  = 15,
+    height = 15,
+    iter   = 500
+))
+
+while (($#)); do
+    getopts ":w:h:i:" arg
+
+    case $arg in
+        w)
+            convert_to_number width  "$2"
+            shift
+            ;;
+        h)
+            convert_to_number height "$2"
+            shift
+            ;;
+        i)
+            convert_to_number iter   "$2"
+            shift
+            ;;
+        *) usage
+    esac
+
+    shift
+done
+
+life
diff --git a/bash/pinwheels/pinwheels b/bash/pinwheels/pinwheels
--- a/bash/pinwheels/pinwheels
+++ b/bash/pinwheels/pinwheels
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
 #
-# pinwheel - pinwheel implementation
-
-cd "${0%.*}"; . ../main
+# pinwheels - pinwheels by @laserbat
 
 RULES=(
     '--+---00000+---++'
@@ -11,70 +9,110 @@ RULES=(
 )
 
 COLORS=(
-    '016 032 041'
     '113 170 197'
-    '237 238 240'
+    '016 032 041'
+    '201 100 126'
 )
 
-usage="usage : ${0##*/} [height] [width] [init] [iter]"
+usage() {
+    while IFS= read -r line; do
+        printf '%s\n' "$line"
+    done << EOF
+usage : ${0##*/} [-whi <number>]
 
-helper X "$1"
-helper Y "$2"
-helper I "$3"
-helper N "$4"
+options :
+    -w <number>    set width  to <number> (default : 15)
+    -h <number>    set height to <number> (default : 15)
+    -i <number>    iterate <number> times (default : 500)
+EOF
+} >&2
 
-declare -A uni
+convert_to_number() {
+    declare -n var=$1
 
-((t = 0))
-
-for ((i = 0; i < I; ++i)) {
-    ((
-        x = RANDOM % X,
-        y = RANDOM % Y
-    ))
-
-    ((uni[$x $y $t] = RANDOM % 2 == 0 ? -1 : 1))
-}
-
-declare -A rules
-
-for i in "${!RULES[@]}"; {
-    for ((j = 0; j < ${#RULES[i]}; ++j)) {
-        case ${RULES[i]:j:1} in
-            +) ((rules[$i $j] =  1));;
-            -) ((rules[$i $j] = -1));;
-            0) ((rules[$i $j] =  0));;
-        esac
+    { printf -v var '%d' "$2" &> /dev/null || ((var < 0)); } || {
+        echo "error : '$2' isn't a valid positive integer" >&2
+        exit 1
     }
 }
 
-for ((n = 0; n < N; ++n)) {
-    out="P3\n$Y $X\n255\n"
+pinwheels() {
+    declare -A rules
 
-    for ((i = 0; i < X; ++i)) {
-        for ((j = 0; j < Y; ++j)) {
-            out+="${COLORS[uni[$i $j $t]]}\n"
-
-            ((cnt = 0))
-
-            for u in -1 0 1; {
-                for v in -1 0 1; {
-                    ((u != 0 || v != 0)) && {
-                        ((
-                            x = (i + u + X) % X,
-                            y = (j + v + Y) % Y
-                        ))
-
-                        ((cnt += uni[$x $y $t]))
-                    }
-                }
-            }
-
-            ((uni[$i $j $((!t))] = rules[$((uni[$i $j $t] + 1)) $((cnt + 8))]))
+    for ((i = 0; i < ${#RULES[@]}; ++i)) {
+        for ((j = 0; j < ${#RULES[i]}; ++j)) {
+            case ${RULES[i]:j:1} in
+                +) ((rules[$i $j] =  1));;
+                -) ((rules[$i $j] = -1));;
+                0) ((rules[$i $j] =  0))
+            esac
         }
     }
 
-    ((t ^= 1))
+    declare -A uni
 
-    printf '%b\n' "$out"
+    ((flag = 0))
+
+    for ((i = 0; i < height * width / 2; ++i)) {
+        ((uni[$((RANDOM % height)) $((RANDOM % width)) $flag] = RANDOM % 2 == 0 ? -1 : 1))
+    }
+
+    for ((n = 0; n < iter; ++n)) {
+        printf 'P3\n%s %s\n255\n' "$width" "$height"
+
+        for ((i = 0; i < height; ++i)) {
+            for ((j = 0; j < width; ++j)) {
+                printf '%s\n' "${COLORS[uni[$i $j $flag] + 1]}"
+
+                ((cnt = 0))
+
+                for ((k = -1; k <= 1; ++k)) {
+                    for ((l = -1; l <= 1; ++l)) {
+                        ((k != 0 || l != 0)) && {
+                            ((
+                                x = (i + k + height) % height,
+                                y = (j + l +  width) %  width
+                            ))
+
+                            ((cnt += uni[$x $y $flag]))
+                        }
+                    }
+                }
+
+                ((uni[$i $j $((!flag))] = rules[$((uni[$i $j $flag] + 1)) $((cnt + 8))]))
+            }
+        }
+
+        ((flag ^= 1))
+    }
 }
+
+((
+    width  = 15,
+    height = 15,
+    iter   = 500
+))
+
+while (($#)); do
+    getopts ":w:h:i:" arg
+
+    case $arg in
+        w)
+            convert_to_number width  "$2"
+            shift
+            ;;
+        h)
+            convert_to_number height "$2"
+            shift
+            ;;
+        i)
+            convert_to_number iter   "$2"
+            shift
+            ;;
+        *) usage
+    esac
+
+    shift
+done
+
+pinwheels
diff --git a/bash/wireworld/wireworld b/bash/wireworld/wireworld
--- a/bash/wireworld/wireworld
+++ b/bash/wireworld/wireworld
@@ -1,14 +1,6 @@
 #!/usr/bin/env bash
 #
-# wireworld - wireworld implementation
-
-cd "${0%.*}"; . ../main
-
-usage="usage : ${0##*/} [file] [iter]"
-
-{ mapfile -t input < "$1"; } 2> /dev/null || die "$usage"
-
-helper N "$2"
+# wireworld - wireworld
 
 COLORS=(
     '016 032 041'
@@ -17,56 +9,105 @@ COLORS=(
     '237 238 240'
 )
 
-declare -A uni
+usage() {
+    while IFS= read -r line; do
+        printf '%s\n' "$line"
+    done << EOF
+usage : ${0##*/} [-i <number>] [file]
 
-((
-    X = ${#input[@]},
-    Y = ${#input[0]}
-))
+options :
+    -i <number>    iterate <number> times (default : 500)
+EOF
+} >&2
 
-((t = 0))
+convert_to_number() {
+    declare -n var=$1
 
-for ((i = 0; i < X; ++i)) {
-    for ((j = 0; j < Y; ++j)) {
-        ((uni[$i $j $t] = ${input[i]:j:1}))
+    { printf -v var '%d' "$2" &> /dev/null || ((var < 0)); } || {
+        echo "error : '$2' isn't a valid positive integer" >&2
+        exit 1
     }
 }
 
-for ((n = 0; n < N; ++n)) {
-    out="P3\n$Y $X\n255\n"
+wireworld() {
+    declare -A uni
 
-    for ((i = 0; i < X; ++i)) {
-        for ((j = 0; j < Y; ++j)) {
-            out+="${COLORS[uni[$i $j $t]]}\n"
+    { mapfile -t input < "$file"; } 2> /dev/null ||
+        usage
 
-            case $((uni[$i $j $t])) in
-                0) ((tmp = 0));;
-                1) ((tmp = 2));;
-                2) ((tmp = 3));;
-                3)
-                    ((cnt = 0))
+    ((
+        height = ${#input[@]},
+        width  = ${#input[0]}
+    ))
 
-                    for u in -1 0 1; {
-                        for v in -1 0 1; {
-                            ((u != 0 || v != 0)) && {
-                                ((
-                                    x = (i + u + X) % X,
-                                    y = (j + v + Y) % Y
-                                ))
+    ((flag = 0))
 
-                                ((uni[$x $y $t] == 1 && ++cnt))
-                            }
-                        }
-                }
-
-                ((tmp = (cnt == 1 || cnt == 2) ? 1 : 3))
-            esac
-
-            ((uni[$i $j $((!t))] = tmp))
+    for ((i = 0; i < height; ++i)) {
+        for ((j = 0; j < width; ++j)) {
+            ((uni[$i $j $flag] = ${input[i]:j:1}))
         }
     }
 
-    ((t ^= 1))
+    for ((n = 0; n < iter; ++n)) {
+        printf 'P3\n%s %s\n255\n' "$width" "$height"
 
-    printf '%b\n' "$out"
+        for ((i = 0; i < height; ++i)) {
+            for ((j = 0; j < width; ++j)) {
+                printf '%s\n' "${COLORS[uni[$i $j $flag]]}"
+
+                case $((uni[$i $j $flag])) in
+                    0) ((tmp = 0));;
+                    1) ((tmp = 2));;
+                    2) ((tmp = 3));;
+                    3)
+                        ((cnt = 0))
+
+                        for ((k = -1; k <= 1; ++k)) {
+                            for ((l = -1; l <= 1; ++l)) {
+                                ((k != 0 || l != 0)) && {
+                                    ((
+                                        x = (i + k + height) % height,
+                                        y = (j + l +  width) %  width
+                                    ))
+
+                                    ((uni[$x $y $flag] == 1)) &&
+                                        ((++cnt))
+                                }
+                            }
+                        }
+
+                    ((tmp = (cnt == 1 || cnt == 2) ? 1 : 3))
+                esac
+
+                ((uni[$i $j $((!flag))] = tmp))
+            }
+        }
+
+        ((flag ^= 1))
+    }
 }
+
+((iter = 500))
+
+file=
+
+while (($#)); do
+    case $1 in
+        -i)
+            [[ $2 ]] \
+                && convert_to_number iter "$2" \
+                || usage
+
+            shift
+            ;;
+        --) break;;
+        -*) usage;;
+         *) file=$1
+     esac
+
+     shift
+done
+
+[[ $file ]] || usage
+
+wireworld
diff --git a/c/disease/run b/c/disease/run
--- a/c/disease/run
+++ b/c/disease/run
@@ -1,22 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-_()
-    if ! type "$1" > /dev/null 2>&1; then
-        echo "error : install $1 first" >&2
-        exit 1
-    fi
+type mpv &> /dev/null || {
+    echo 'error : install mpv first' >&2
+    exit 1
+}
 
-_ mpv
-_ wattr
+make
 
-./make.sh
-
-# run based on screen resolution
-wattr hw "$(lsw -r)" | {
-    read -r h w
-
-./disease $((h / 2)) \
-          $((w / 2)) \
-          500
-} |
-    mpv - -fs -scale=nearest
+"bin/${PWD##*/}" | mpv - -fs -scale=nearest
