add checks for mpv

diff --git a/1d/run b/1d/run
--- a/1d/run
+++ b/1d/run
@@ -2,6 +2,11 @@
 #
 # outputs to mpv
 
+if ! command -v mpv > /dev/null; then
+    echo 'error : install mpv first' >&2
+    exit 1
+if
+
 ./make.sh
 
 ./1d $((RANDOM % 256)) \
diff --git a/pinwheels/run b/pinwheels/run
--- a/pinwheels/run
+++ b/pinwheels/run
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! command -v mpv > /dev/null; then
+    echo 'error : install mpv first' >&2
+    exit 1
+if
+
 ./make.sh
 
 wattr hw "$(lsw -r)" | {
